import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AnimatedLayout from '../components/AnimatedLayout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <header className="bg-background py-4 border-b border-secondary-200">
            <div className="container mx-auto px-4 flex items-center justify-between">
              <nav className="flex flex-col sm:flex-row sm:space-x-4 space-y-2 sm:space-y-0">
                <Link href="/" className="text-secondary-700 hover:text-primary hover:underline">首页</Link>
                <Link href="/search" className="text-secondary-700 hover:text-primary hover:underline">搜索</Link>
              </nav>
            </div>
          </header>
          <main className="container mx-auto px-4 flex-1 py-8 prose prose-primary">
            <AnimatedLayout>
              {children}
            </AnimatedLayout>
          </main>
          <footer className="bg-background py-4">
            <div className="container mx-auto px-4 text-center text-sm text-secondary">
              © {new Date().getFullYear()} 镜头图书馆. 保留所有权利.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
